version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - node.master=true
      - node.data=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    ports:
      - 5044:5044
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
      - ./ssl:/opt/ssl
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://es:9200
      - pipeline.workers=1

volumes:
  data:
    driver: local
